#!/usr/bin/python3

# Copyright © 2014 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import argparse
import errno
import glob
import os
import re
import sys
import urllib.parse
import xml.etree.ElementTree as etree

# https://tools.ietf.org/html/rfc3986#section-2
re_url = re.compile(
    br'''
    http://
    (?:
      [\[\]:/?#@]  # gen-delims
    | [!$&'()*+,;=]  # sub-delims
    | [a-zA-Z0-9._~-]  # unreserved
    | % [0-9a-fA-F]{2}  # percent-encoding
    )+
    ''',
    re.VERBOSE,
)

class log(object):

    verbose = None
    file = sys.stderr

    def msg(self, s, *args, **kwargs):
        if not self.verbose:
            return
        s = s.format(*args, **kwargs)
        print(s, file=self.file)
        self.file.flush()

    def start(self, s, *args, **kwargs):
        if not self.verbose:
            return
        s = s.format(*args, **kwargs)
        print(s, end=' ... ', file=self.file)
        self.file.flush()

    end = msg

log = log()

class Rule(object):

    class SyntaxError(RuntimeError):
        pass

    class SubstError(RuntimeError):
        pass

    def __init__(self, pattern, repl, *, downgrade=False):
        # FIXME: Python and JS syntax are not quite compatible
        try:
            pattern = pattern.replace(')?', '|)')
            self.regexp = re.compile(pattern)
        except re.error as exc:
            raise self.SyntaxError(
                'regexp syntax error: {}: {!r}'.format(exc, pattern)
            )
        self.repl = repl.replace('$', '\\')
        self.downgrade = downgrade

    def apply(self, url):
        # FIXME: take .downgrade into account
        try:
            result = self.regexp.sub(self.repl, url)
        except re.error as exc:
            raise self.SubstError(
                'regexp substitution error: {}: {!r} ~ {!r}'.format(
                    exc,
                    self.regexp.pattern,
                    self.repl,
                )
            )
        return result

class Ruleset(object):

    class SyntaxError(RuntimeError):
        pass

    def __init__(self):
        self.name = None
        self.platform = None
        self.default_off = False
        self.targets = set()
        self.exclusions = None
        self.rules = []

    @classmethod
    def from_xml_node(cls, node):
        self = cls()
        attr = node.attrib.copy()
        try:
            self.name = attr.pop('name')
        except KeyError:
            raise cls.SyntaxError('missing name for <ruleset>')
        self.platform = attr.pop('platform', None)
        self.default_off = attr.pop('default_off', False)
        if attr:
            raise cls.SyntaxError(
                'unexpected <ruleset> attributes: {attr}'.format(
                    attr=', '.join(attr.keys())
                )
            )
        targets = []
        exclusions = []
        for node in node:
            attr = node.attrib.copy()
            if node.tag == 'rule':
                try:
                    pattern = attr.pop('from')
                except KeyError:
                    raise cls.SyntaxError('missing source for <rule>')
                try:
                    repl = attr.pop('to')
                except KeyError:
                    raise cls.SyntaxError('missing target for <rule>')
                downgrade = attr.pop('downgrade', False)
                rule = Rule(pattern, repl, downgrade=downgrade)
                self.rules += [rule]
            elif node.tag == 'securecookie':
                attr.clear()
            elif node.tag == 'target':
                try:
                    host = attr.pop('host')
                except KeyError:
                    raise cls.SyntaxError('missing host for <target>')
                targets += [host]
            elif node.tag == 'exclusion':
                try:
                    pattern = attr.pop('pattern')
                except KeyError:
                    raise cls.SyntaxError('missing patter for <exclusion>')
                exclusions += [pattern]
            elif node.tag == 'test':
                attr.pop('url')
            else:
                raise cls.SyntaxError(
                    'unexpected <ruleset> child: <{tag}>'.format(
                        tag=node.tag
                    )
                )
            if attr:
                raise cls.SyntaxError(
                    'unexpected <{tag}> attributes: {attr}'.format(
                        tag=node.tag,
                        attr=', '.join(attr.keys())
                    )
                )
        self.targets = r'\A(?:{})\Z'.format('|'.join(
            re.escape(t).replace(re.escape('*'), '.+') for t in targets
        ))
        self.targets = re.compile(self.targets)
        if exclusions:
            # FIXME: Python and JS syntax are not quite compatible
            self.exclusions = '|'.join(exclusions)
            self.exclusions = re.compile(self.exclusions)
        return self

    def is_matching_target(self, domain):
        return self.targets.match(domain)

    def apply(self, url):
        if self.default_off:
            return url
        if self.platform is not None:
            return url
        if self.exclusions is not None:
            if self.exclusions.match(url):
                return url
        if url.startswith('https://'):
            return url
        for rule in self.rules:
            url = rule.apply(url)
            if url.startswith('https://'):
                return url

    def __repr__(self):
        return '<Ruleset {!r}>'.format(self.name)

class RulesetGroup(object):

    def __init__(self):
        self.rulesets = set()

    def add(self, rs):
        self.rulesets.add(rs)

    def get_relevant_rulesets(self, url):
        purl = urllib.parse.urlparse(url)
        domain = purl.netloc
        return (
            rs for rs in self.rulesets
            if rs.is_matching_target(domain)
        )

    def apply(self, url):
        for rs in self.get_relevant_rulesets(url):
            new_url = rs.apply(url)
            if new_url is not None:
                return new_url
        return url

def load_rulesets(directory):
    wildcard = os.path.join(directory, '*.xml')
    rg = RulesetGroup()
    paths = glob.glob(wildcard)
    if not paths:
        raise OSError(errno.ENOENT, 'no such files', wildcard)
    for path in paths:
        with open(path, 'rb') as ruleset_fp:
            tree = etree.parse(ruleset_fp)
            ruleset = Ruleset.from_xml_node(tree.getroot())
            rg.add(ruleset)
    return rg

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ruleset', '-R', metavar='<directory>', required=True, help='path to HTTPS everywhere rulesets')
    ap.add_argument('--verbose', '-v', action='store_true', help='be more verbose')
    ap.add_argument('paths', metavar='<file>', nargs='+')
    options = ap.parse_args()
    log.verbose = options.verbose
    log.start('loading ruleset {}', options.ruleset)
    rg = load_rulesets(options.ruleset)
    log.end('ok')
    for path in options.paths:
        log.msg('checking {}', path)
        with open(path, 'rb') as file:
            for line in file:
                for url in re_url.findall(line):
                    url = url.decode('ASCII')
                    new_url = rg.apply(url)
                    if url != new_url:
                        print(url, '->', new_url)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
